Adds a top level package description
rails/thor pull request #671
Opened 2019-08-13 15:18 UTC by afiune

There could be cases where users have a very short name for the package
name, which is the cli name, in such cases it would be good to provide a
way to add a top-level package description just like there is for
sub-commands.

## Example.

With the following class:
```
class Marvel < Thor
  package_name "marvel"
  package_description "A command-line interpreter for the Marvel Corporation."
end
```

We would see the follosing help:
```
$ marvel help
A command-line interpreter for the Marvel Corporation.

marvel commands:
```

Signed-off-by: Salim Afiune <afiune@chef.io>

2019-08-20 09:41 UTC, afiune commented
@rafaelfranca hi! 👋 curious to know if this contribution makes sense to the project? 😃

2019-09-16 19:25 UTC, afiune commented on lib/thor.rb
> +    def package_description(description, _ = {})
Since they are top-level description, I think so, but do you see a different approach? I would be interested to hear it.

2021-06-01 14:16 UTC, dorner requested changes

2021-06-01 14:16 UTC, dorner commented on lib/thor.rb
> +    def package_description(description, _ = {})
You could just not have this argument at all? The `package_description` method could just take one argument.

2022-07-05 21:52 UTC, closed without merging